#!/bin/sh

# Cleanup for past runs
rm -f __key __name __template __template.asc

# Get public key from clipboard
pbpaste > __key

# Import public key and save the name to a file
gpg --import __key 2>&1 | ag --nocolor -o '(?<=key )[^:]+' > __name

# Copy template and open for the user
cp my-template __template
vim __template

# Encode Message
gpg --sign --encrypt --symmetric --armor --local-user $1 --recipient $(cat __name) __template

# VIM Contents
cat __template.asc | pbcopy
gpg --decrypt __template.asc

# Cleanup for past runs
rm -f __key __name __template __template.asc
